<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>个人博客</title>
<meta name="keywords" content="个人博客" />
<meta name="description" content="个人博客" />

<!--[if lt IE 9]>
<script src="/public/yanqq/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header>
  <div id="logo"><a href="/"></a></div>
  <nav class="topnav" id="topnav"><a href="/blog/index"><span>首页</span><span class="en">Protal</span></a><a href="/blog/newlist"><span>随笔</span><span class="en">Lean</span></a><a href="/blog/moodlist"><span>杂谈</span><span class="en">Relax</span></a><a href="#"><span>留言版</span><span class="en">Gustbook</span></a></nav>
  <!--
  <nav class="topnav" id="topnav"><a href="/blog/index"><span>首页</span><span class="en">Protal</span></a><a href="#"><span>LINUX</span><span class="en">Linux</span></a><a href="/blog/newlist"><span>PHP</span><span class="en">Php</span></a><a href="/blog/moodlist"><span>MYSQL</span><span class="en">Mysql</span></a><a href="/blog/share"><span></span><span class="en">Share</span></a><a href="/blog/knowledge"><span>杂谈</span><span class="en">Learn</span></a><a href="#"><span>留言版</span><span class="en">Gustbook</span></a></nav>
  </nav>-->
</header>
