

<div class="sidebar-wrap">
        <div class="sidebar-title">
            <h1>菜单</h1>
        </div>
        <div class="sidebar-content">
            <ul class="sidebar-list">
                <li>
                    <a href="#"><i class="icon-font">&#xe003;</i>常用操作</a>
                    <ul class="sub-menu">
                        <li><a href="/admin/editBlog"><i class="icon-font">&#xe005;</i>随笔</a></li>
                        <li><a href="/admin/publish"><i class="icon-font">&#xe006;</i>杂谈</a></li>
                        <!--<li><a href="customer-课程出售.html"><i class="icon-font">&#xe008;</i>课程出售</a></li>-->
                    </ul>
					<a href="#"><i class="icon-font">&#xe003;</i>列表</a>
                    <ul class="sub-menu">
                        <li><a href="/"><i class="icon-font">&#xe005;</i>随笔列表</a></li>
                        <li><a href="/admin/editMoodlist"><i class="icon-font">&#xe006;</i>杂谈列表</a></li>
                        <!--<li><a href=""><i class="icon-font">&#xe008;</i>课程出售</a></li>-->
                    </ul>
                </li>
            </ul>
        </div>
    </div>
