<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="keywords" content="JS代码,其他代码,JS广告代码,JS特效代码" />
<meta name="description" content="此代码内容为鼠标左右滑动的手机页面切换效果，属于站长常用代码，更多其他代码代码请访问懒人图库JS代码频道。" />
<title>鼠标左右滑动的手机页面切换效果_懒人图库</title>
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
<!--CSS--->
<link href="/public/css/voice/main.css" rel="stylesheet"/>
<!--Plugins--->
<script type="text/javascript" src="/public/js/voice/jquery.min.js"></script>
<script type="text/javascript" src="/public/js/voice/hammer.min.js"></script>
<script type="text/javascript" src="/public/js/voice/hammer.jquery.min.js"></script>
<script type="text/javascript" src="/public/js/voice/itemslide.min.js"></script>
<!--Scripts--->
<script type="text/javascript" src="/public/js/voice/sliding.js"></script>
</head>
<body>
<!-- 代码 开始 -->
    <ul>
        <li>
            <div id="blackcover">
				<h1 style="color:#F00">请用鼠标单击左右滑动查看效果！</h1>
				<div style="text-align:center;margin:50px 0">
				<p>来源：<a href="http://itemslide.github.io/" target="_blank">itemslide</a>　代码整理：<a href="http://www.lanrentuku.com/" target="_blank">懒人图库</a>　感谢：<a href="http://blog.hexccc.com/service/" target="_blank">wordpress Xcoder</a></p>
				<p>＊尊重他人劳动成果，转载请自觉注明出处！注：此代码仅供学习交流，请勿用于商业用途。</p>
				<p></p>
				<p><p>鼠标左右滑动的手机页面切换效果，兼容主流浏览器，懒人图库推荐下载！</p><p><br /></p><p>使用方法：</p><p>1、head区域引用一下代码</p><p>&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width&quot;&gt;</p><p>2、head区域引入css和js文件</p><p>3、一个页面对应一个li标签</p><p>4、复制js, css文件夹里的图片到相应的路径</p></p>
				<p style="margin:20px 0"></p>
				</div>
			</div>
        </li>
        <li>
            <h1>懒人图库</h1>
			<p>一个页面对应一个li标签,请再用鼠标滑动</p>
        </li>
	    <li>
            <h1>本效果由懒人图库整理</h1><br />
            更多代码请访问：<a href="http://www.lanrentuku.com/js/" target="_blank">懒人图库</a>
        </li>
    </ul>
<!-- 代码 结束 -->

</body>
</html>