<?php new Ui_Common_BlogHeader();?>

<link href="/public/yanqq/css/base.css" rel="stylesheet">
<link href="/public/yanqq/css/index.css" rel="stylesheet">

<div class="banner">
  <section class="box">
    <ul class="texts">
      <p>打了死结的青春，捆死一颗苍白绝望的灵魂。</p>
      <p>为自己掘一个坟墓来葬心，红尘一梦，不再追寻。</p>
      <p>加了锁的青春，不会再因谁而推开心门。</p>
    </ul>
    <div class="avatar"><a href="#"><span>ppiezhao</span></a> </div>
  </section>
</div>
<div class="template">
  <div class="box">
    <h3>
      <p><span>个人博客</span>模板 Templates</p>
    </h3>
    <ul>
      <li><a href="#"  target="_blank"><img src="/public/yanqq/img/01.jpg"></a><span>仿新浪博客风格·梅——古典个人博客模板</span></li>
      <li><a href="#" target="_blank"><img src="/public/yanqq/img/02.jpg"></a><span>黑色质感时间轴html5个人博客模板</span></li>
      <li><a href="#"  target="_blank"><img src="/public/yanqq/img/03.jpg"></a><span>Green绿色小清新的夏天-个人博客模板</span></li>
      <li><a href="#" target="_blank"><img src="/public/yanqq/img/04.jpg"></a><span>女生清新个人博客网站模板</span></li>
      <li><a href="#"  target="_blank"><img src="/public/yanqq/img/02.jpg"></a><span>黑色质感时间轴html5个人博客模板</span></li>
      <li><a href="#"  target="_blank"><img src="/public/yanqq/img/03.jpg"></a><span>Green绿色小清新的夏天-个人博客模板</span></li>
    </ul>
  </div>
</div>
<article>
  <h2 class="title_tj">
    <p>文章<span>推荐</span></p>
  </h2>
  <div class="bloglist left" id = "blog">
	
  </div>
  <!--
  <aside class="right">
    <div class="weather"><iframe width="250" scrolling="no" height="60" frameborder="0" allowtransparency="true" src="http://i.tianqi.com/index.php?c=code&id=12&icon=1&num=1"></iframe></div>
    <div class="news">
    <h3>
      <p>最新<span></span></p>
    </h3>
    <ul class="rank">
      <li><a href="/" title="Column 三栏布局 个人网站模板" target="_blank">Column 三栏布局 个人网站模板</a></li>
      <li><a href="/" title="with love for you 个人网站模板" target="_blank">with love for you 个人网站模板</a></li>
      <li><a href="/" title="免费收录网站搜索引擎登录口大全" target="_blank">免费收录网站搜索引擎登录口大全</a></li>
      <li><a href="/" title="做网站到底需要什么?" target="_blank">做网站到底需要什么?</a></li>
      <li><a href="/" title="企业做网站具体流程步骤" target="_blank">企业做网站具体流程步骤</a></li>
      <li><a href="/" title="建站流程篇——教你如何快速学会做网站" target="_blank">建站流程篇——教你如何快速学会做网站</a></li>
      <li><a href="/" title="box-shadow 阴影右下脚折边效果" target="_blank">box-shadow 阴影右下脚折边效果</a></li>
      <li><a href="/" title="打雷时室内、户外应该需要注意什么" target="_blank">打雷时室内、户外应该需要注意什么</a></li>
    </ul>
    <h3 class="ph">
      <p>点击<span>排行</span></p>
    </h3>
    <ul class="paih">
      <li><a href="/" title="Column 三栏布局 个人网站模板" target="_blank">Column 三栏布局 个人网站模板</a></li>
      <li><a href="/" title="withlove for you 个人网站模板" target="_blank">with love for you 个人网站模板</a></li>
      <li><a href="/" title="免费收录网站搜索引擎登录口大全" target="_blank">免费收录网站搜索引擎登录口大全</a></li>
      <li><a href="/" title="做网站到底需要什么?" target="_blank">做网站到底需要什么?</a></li>
      <li><a href="/" title="企业做网站具体流程步骤" target="_blank">企业做网站具体流程步骤</a></li>
    </ul>
    <h3 class="links">
      <p>友情<span>链接</span></p>
    </h3>
    <ul class="website">
      <li><a href="/">个人博客</a></li>
      <li><a href="/">谢泽文个人博客</a></li>
      <li><a href="/">3DST技术网</a></li>
      <li><a href="/">思衡网络</a></li>
    </ul> 
    </div>  
    
    <a href="/" class="weixin"> </a></aside>
	
	-->
	<?php new Ui_Common_BlogRight();?>
</article>

<script src="/public/yanqq/js/silder.js"></script>

<script type="text/javascript" src="/public/le/js/jquery.min.js"></script>
<script src="/public/yanqq/js/blog_right.js"></script>
<script>
entermore();

function entermore(){
	//alert(1);
	//$("#blog").html('111111');
	$.post('/index/entermoreAjax',{
		data:0
	},function(data){
		if(data.type==0){
			alert("博主很懒！暂无博文！");
		}else{
			
			var html = '';
			var data = data.data;
			
			var len = data.length;
			for(var i=0;i<len;i++){
				
				html += '<h3><a href="/blog/new/id/'+data[i].id+'" >'+data[i].abstract+'</a></h3>'+
				'<figure></figure>'+
				'<ul>'+
				 ' <p>'+data[i].mainbody+'</p>'+
				  '<a title="【活动作品】柠檬绿兔小白个人博客模板" href="/blog/new/id/'+data[i].id+'"  target="_blank" class="readmore">阅读全文>></a>'+
				'</ul>'+
				'<p class="dateview"><span>2015-04-10</span><span>作者：杨青</span><span>个人博客：[<a href=/download/div/>原创个人博客模板</a>]</span></p>';
				
				/* //'<figure><img src="'+data[i].img+'"></figure>'+
				html +=	'<h3>'+data[i].abstract+'</h3>'+
				'<figure></figure>'+
				'<ul>'+
					'<p>'+data[i].mainbody+'</p>'+
					'<a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>'+
				'</ul>'+
				'<p class="dateview"><span>2013-11-04</span><span>作者：杨青</span><span>个人博客：[<a href="/news/life/">程序人生</a>]</span></p>'; */
				
			}
			//alert(html);
			$("#blog").html(html);
			
			
			
		}
	},'json');
}
</script>
</body>
</html>
