<?php new Ui_Common_BlogHeader();?>

<link href="/public/yanqq/css/base.css" rel="stylesheet">
<link href="/public/yanqq/css/new.css" rel="stylesheet">

<article class="blogs">
  <h1 class="t_nav"><span>您当前的位置：<a href="/">首页</a>&nbsp;&gt;&nbsp;<a href="/news/s/">杂谈</a>&nbsp;&gt;&nbsp;<a href="/news/s/">日记</a></span><a href="/" class="n1">网站首页</a><a href="/" class="n2">日记</a></h1>
  <div class="index_about">
    <!--<h2 class="c_titile">爱情不容有错，即使错了那就重来</h2>
    <p class="box_c"><span class="d_time">发布时间：2013-09-08</span><span>编辑：杨青</span><span>互动QQ群：<a href="http://wp.qq.com/wpa/qunwpa?idkey=d4d4a26952d46d564ee5bf7782743a70d5a8c405f4f9a33a60b0eec380743c64">280998807</a></span></p>-->
	<p class="box_c"><span class="d_time">发布时间：<?php echo $result[0]['time']?></span><span>编辑：</span></p>
    <ul class="infos">
    <?php echo $result[0]['mainbody']?>  
    </ul>
	<!--
    <div class="keybq">
    <p><span>关键字词</span>：爱情,犯错,原谅,分手</p>
    
    </div>
    -->
    <div class="nextinfo">
      <p>上一篇：<?php if(!empty($resultpre)): ?><a href="/blog/new/id/<?php echo $resultpre[0]['id'];?>"><?php echo $resultpre[0]['abstract'];?></a></p><?php else: echo "暂无"; endif;?>
      <p>下一篇：<?php if(!empty($resultlast)): ?><a href="/blog/new/id/<?php echo $resultlast[0]['id'];?>"><?php echo $resultlast[0]['abstract'];?></a></p><?php else: echo "暂无"; endif;?>
    </div>
	<!--
    <div class="otherlink">
      <h2>相关文章</h2>
      <ul>
        <li><a href="/news/s/2013-07-25/524.html" title="现在，我相信爱情！">现在，我相信爱情！</a></li>
        <li><a href="/newstalk/mood/2013-07-24/518.html" title="我希望我的爱情是这样的">我希望我的爱情是这样的</a></li>
        <li><a href="/newstalk/mood/2013-07-02/335.html" title="有种情谊，不是爱情，也算不得友情">有种情谊，不是爱情，也算不得友情</a></li>
        <li><a href="/newstalk/mood/2013-07-01/329.html" title="世上最美好的爱情">世上最美好的爱情</a></li>
        <li><a href="/news/read/2013-06-11/213.html" title="爱情没有永远，地老天荒也走不完">爱情没有永远，地老天荒也走不完</a></li>
        <li><a href="/news/s/2013-06-06/24.html" title="爱情的背叛者">爱情的背叛者</a></li>
      </ul>
    </div>-->
  </div>
  <?php new Ui_Common_BlogRight();?>
</article>

<script src="/public/yanqq/js/silder.js"></script>
<script type="text/javascript" src="/public/le/js/jquery.min.js"></script>
<script src="/public/yanqq/js/blog_right.js"></script>
</body>
</html>