<?php new Ui_Common_BlogHeader();?>

<link href="/public/yanqq/css/base.css" rel="stylesheet">
<link href="/public/yanqq/css/style.css" rel="stylesheet">

<article class="blogs">
<h1 class="t_nav"><span>记录工作中，学习中遇到各种。。。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">随笔</a></h1>
<div class="newblog left">
	<div id = "blog">
   <!--<h2>程序员请放下你的技术情节，与你的同伴一起进步</h2>
   <p class="dateview"><span>发布时间：2013-11-04</span><span>作者：杨青</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>
    <figure><img src="/public/yanqq/img/001.png"></figure>
    <ul class="nlist">
      <p>如果说掌握一门赖以生计的技术是技术人员要学会的第一课的话， 那么我觉得技术人员要真正学会的第二课，不是技术，而是业务、交流与协作，学会关心其他工作伙伴的工作情况和进展...</p>
      <a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>
    </ul>
    <div class="line"></div>
     <h2>程序员请放下你的技术情节，与你的同伴一起进步</h2>
   <p class="dateview"><span>发布时间：2013-11-04</span><span>作者：杨青</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>
    <figure><img src="/public/yanqq/img/001.png"></figure>
    <ul class="nlist">
      <p>如果说掌握一门赖以生计的技术是技术人员要学会的第一课的话， 那么我觉得技术人员要真正学会的第二课，不是技术，而是业务、交流与协作，学会关心其他工作伙伴的工作情况和进展...</p>
      <a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>
    </ul>
    <div class="line"></div>
         <h2>程序员请放下你的技术情节，与你的同伴一起进步</h2>
   <p class="dateview"><span>发布时间：2013-11-04</span><span>作者：杨青</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>
    <figure><img src="/public/yanqq/img/001.png"></figure>
    <ul class="nlist">
      <p>如果说掌握一门赖以生计的技术是技术人员要学会的第一课的话， 那么我觉得技术人员要真正学会的第二课，不是技术，而是业务、交流与协作，学会关心其他工作伙伴的工作情况和进展...</p>
      <a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>
    </ul>
    <div class="line"></div>
         <h2>程序员请放下你的技术情节，与你的同伴一起进步</h2>
   <p class="dateview"><span>发布时间：2013-11-04</span><span>作者：杨青</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>
    <figure><img src="/public/yanqq/img/001.png"></figure>
    <ul class="nlist">
      <p>如果说掌握一门赖以生计的技术是技术人员要学会的第一课的话， 那么我觉得技术人员要真正学会的第二课，不是技术，而是业务、交流与协作，学会关心其他工作伙伴的工作情况和进展...</p>
      <a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>
    </ul>-->
	</div>
	
    <div class="line"></div>
    <div class="blank"></div>
    
    <div class="page"></div>
</div>
<!--
<aside class="right">
   <div class="rnav">
      <ul>
       <li class="rnav1"><a href="/download/" target="_blank">日记</a></li>
       <li class="rnav2"><a href="/newsfree/" target="_blank">程序人生</a></li>
       <li class="rnav3"><a href="/web/" target="_blank">欣赏</a></li>
       <li class="rnav4"><a href="/newshtml5/" target="_blank">短信祝福</a></li>
     </ul>      
    </div>
<div class="news">
<h3>
      <p>最新<span></span></p>
    </h3>
    <ul class="rank">
      <li><a href="/" title="Column 三栏布局 个人网站模板" target="_blank">Column 三栏布局 个人网站模板</a></li>
      <li><a href="/" title="with love for you 个人网站模板" target="_blank">with love for you 个人网站模板</a></li>
      <li><a href="/" title="免费收录网站搜索引擎登录口大全" target="_blank">免费收录网站搜索引擎登录口大全</a></li>
      <li><a href="/" title="做网站到底需要什么?" target="_blank">做网站到底需要什么?</a></li>
      <li><a href="/" title="企业做网站具体流程步骤" target="_blank">企业做网站具体流程步骤</a></li>
      <li><a href="/" title="建站流程篇——教你如何快速学会做网站" target="_blank">建站流程篇——教你如何快速学会做网站</a></li>
      <li><a href="/" title="box-shadow 阴影右下脚折边效果" target="_blank">box-shadow 阴影右下脚折边效果</a></li>
      <li><a href="/" title="打雷时室内、户外应该需要注意什么" target="_blank">打雷时室内、户外应该需要注意什么</a></li>
    </ul>
    <h3 class="ph">
      <p>点击<span>排行</span></p>
    </h3>
    <ul class="paih">
      <li><a href="/" title="Column 三栏布局 个人网站模板" target="_blank">Column 三栏布局 个人网站模板</a></li>
      <li><a href="/" title="withlove for you 个人网站模板" target="_blank">with love for you 个人网站模板</a></li>
      <li><a href="/" title="免费收录网站搜索引擎登录口大全" target="_blank">免费收录网站搜索引擎登录口大全</a></li>
      <li><a href="/" title="做网站到底需要什么?" target="_blank">做网站到底需要什么?</a></li>
      <li><a href="/" title="企业做网站具体流程步骤" target="_blank">企业做网站具体流程步骤</a></li>
    </ul>
    </div>
    <div class="visitors">
      <h3><p>最近访客</p></h3>
      <ul>

      </ul>
    </div>
       
</aside>
-->
<?php new Ui_Common_BlogRight();?>
</article>

<script src="/public/yanqq/js/silder.js"></script>
<script type="text/javascript" src="/public/le/js/jquery.min.js"></script>
<script src="/public/yanqq/js/blog_right.js"></script>
<script>

$(document).on('click', '.preall', function () {
	entermore(1);
})

$(document).on('click', '.preone', function () {
	var id = $('.now').html();
	id = parseInt(id)-1;
	entermore(id);
})

$(document).on('click', '.midden', function () {
	var id = $(this).html();
	entermore(id);
})
$(document).on('click', '.lastone', function () {
	var id = $('.now').html();
	id = parseInt(id)+1;
	entermore(id);
})
$(document).on('click', '.endlast', function () {
	var id = $('.endlast').attr('for');
	entermore(id);
})

entermore(1);
function entermore(_id){
	var start = _id;
	//alert(1);
	//$("#blog").html('111111');
	$.post('/blog/newlistAjax',{
		start:start
	},function(dataa){
		if(dataa.type==0){
			alert("博主很懒！暂无博文！");
		}else{
			
			var html = '';
			var data = dataa.data;
			
			var len = data.length;
			for(var i=0;i<len;i++){
				//<figure><img src="'+data[i].img+'"></figure>
				//<p class="dateview"><span>发布时间：'+data[i].created+'</span><span>作者：</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>
				html +=	'<h2>'+data[i].abstract+'</h2>'+
			   '<p class="dateview"><span>发布时间：'+data[i].created+'</span><span>作者：</span><span>分类：[]</span></p>'+
				
				'<ul class="nlist">'+
				  '<p>'+data[i].mainbody+'</p>'+
				  '<a title="/" href="/blog/new/id/'+data[i].id+'" target="_blank" class="readmore">阅读全文>></a>'+
				'</ul>'+
				'<div class="line"></div>';
				
				/* html +=	'<h2>'+data[i].abstract+'</h2>'+
				'<p class="dateview"><span>发布时间：2013-11-04</span><span>作者：杨青</span><span>分类：[<a href="/news/life/">程序人生</a>]</span></p>'+
				'<figure></figure>'+
				'<ul class="nlist">'+
					'<p>'+data[i].mainbody+'</p>'+
					'<a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>'+
				'</ul><div class="line"></div>'; */
				
				
				/* html +=	'<h3>'+data[i].abstract+'</h3>'+
				'<figure><img src="'+data[i].img+'"></figure>'+
				'<ul>'+
					'<p>'+data[i].mainbody+'</p>'+
					'<a title="/" href="/" target="_blank" class="readmore">阅读全文>></a>'+
				'</ul>'+
				'<p class="dateview"><span>2013-11-04</span><span>作者：杨青</span><span>个人博客：[<a href="/news/life/">程序人生</a>]</span></p>'; */
				
			}
			//alert(html);
			$("#blog").html(html);
			$(".page").html(dataa.page);
			
			
		}
	},'json');
}
</script>
</body>
</html>