<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Swiper demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" type="text/css" charset="utf-8" href="/public/css/swiper/swiper.min.css">

    <!-- Demo styles -->
    <style>
    html, body {
        position: relative;
        height: 100%;
    }
    body {
        background: #eee;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color:#000;
        margin: 0;
        padding: 0;
    }
    .x {
        width: 100%;
        height: 100%;;
        margin: 20px auto;
    }
	.y {
        width: 100%;;
        height: 100%;;
        margin: 20px auto;
    }
    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }
    </style>
</head>
<body>
    <!-- Swiper -->
    <div class="swiper-container x" >
        <div class="swiper-wrapper">
            <div class="swiper-slide">
				<div class="swiper-container y"  >
					<div class="swiper-wrapper">
						<div class="swiper-slide test0">Slide 11y</div>
						<div class="swiper-slide test1">Slide 21y</div>
					</div>
				</div>
			</div>
            <div class="swiper-slide">
				<div class="swiper-container y"  >
				<div class="swiper-wrapper">
						<div class="swiper-slide test0">Slide 21y</div>
						<div class="swiper-slide test1">Slide 22y</div>
					</div>
				</div>
			</div>
            <div class="swiper-slide">Slide 3x</div>
            <div class="swiper-slide">Slide 4x</div>
            <div class="swiper-slide">Slide 5x</div>
            <div class="swiper-slide">Slide 6x</div>
            <div class="swiper-slide">Slide 7x</div>
            <div class="swiper-slide">Slide 8x</div>
            <div class="swiper-slide">Slide 9x</div>
            <div class="swiper-slide">Slide 10x</div>
        </div>
        <!-- Add Pagination 
        <div class="swiper-pagination"></div>-->
    </div>
	
	

    <!-- Swiper JS -->
	<script type="text/javascript" charset="utf-8" src="/public/js/swiper/jquery.min.js"></script>
	<script type="text/javascript" charset="utf-8" src="/public/js/swiper/swiper.min.js"></script>
	

    <!-- Initialize Swiper -->
    <script>
	
    
		//$(document).ready(function(){
	
	 		var swiper = new Swiper('.y', {
				pagination: '.swiper-pagination',
				paginationClickable: true,
				direction: 'vertical',
				onInit: function(swiper){
						  //Swiper初始化了
						 // alert(swiper.activeIndex);//提示Swiper的当前索引
				},
				onSlidePrevEnd: function(swiper){
					
				},onSlideNextEnd: function(swiper){
					
				}


			});
			var swipera = new Swiper('.x',{
					onInit: function(swiper){
						  //Swiper初始化了
						  //alert(swiper.activeIndex);//提示Swiper的当前索引
					},
					onSlidePrevEnd: function(swiper){
						//alert("test"+swiper.activeIndex);
						
					},onSlideNextEnd: function(swiper){
						//alert("test"+swiper.activeIndex);
						
					}
			});
		//});
    </script>
</body>
</html>